name: build-test

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build

      - run: npm run test

  send-success-notification:
    runs-on: ubuntu-latest
    if: success('build_test')
    steps:
      - name: Send Success Message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'W3bLocker'
          DISCORD_AVATAR: 'https://i.imgur.com/BPnQGGY.jpeg'
          DISCORD_EMBEDS: '[{"color":39423,"title":"${{ github.event.pull_request.title }}","url":"${{ github.event.pull_request.html_url }}", "author": {"name": "${{ github.event.pull_request.user.login}}", "icon_url": "${{ github.event.pull_request.user.avatar_url }}", "url": "${{ github.event.pull_request.user.html_url}}"}, "description":"Branch: ${{ github.event.pull_request.base.ref }}","timestamp":"${{ github.event.pull_request.updated_at }}","footer":{"text":"${{ github.event.repository.full_name }}","icon_url":"${{ github.event.repository.owner.avatar_url }}"}}]'
        uses: Ilshidur/action-discord@master

  send-failure-notification: 
    runs-on: ubuntu-latest
    if: failure('build_test')
    steps:
      - name: Send Failure Message to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'W3bLocker'
          DISCORD_AVATAR: 'https://i.imgur.com/BPnQGGY.jpeg'
          DISCORD_EMBEDS: '[{"color":16189448,"title":"${{ github.event.pull_request.title }}","url":"${{ github.event.pull_request.html_url }}", "author": {"name": "${{ github.event.pull_request.user.login}}", "icon_url": "${{ github.event.pull_request.user.avatar_url }}", "url": "${{ github.event.pull_request.user.html_url}}"}, "description":"SOMETHING GOT WRONG. CHECK LOGS IN GITHUB ACTIONS!","timestamp":"${{ github.event.pull_request.updated_at }}","footer":{"text":"${{ github.event.repository.full_name }}","icon_url":"${{ github.event.repository.owner.avatar_url }}"}}]'
        uses: Ilshidur/action-discord@master
      # - name: Discord notification - Test Failure
      #   if: failure()
      #   env:
      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #     DISCORD_USERNAME: BOTJÃO
      #     DISCORD_EMBEDS: '[{"title": "Run all test","color": 16711680, "description": "Some test brake."}]'
      #   uses: Ilshidur/action-discord@master
      #   with:
      #     args: 'Project: {{ EVENT_PAYLOAD.repository.full_name }}'
