name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Check npm ci
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    #   - run: npm run build --if-present
    #     if: failure()
    #     with:
    #       severity: error
    #       details: Build Failed!
    #       webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    #   - run: npm test
    #     if: failure()
    #     with:
    #       severity: error
    #       details: Test Failed!
    #       webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    # if: failure()
    #   with:
    #     severity: error
    #     details: Action Failed!
    #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    # if: success()
    #   with:
    #     severity: info
    #     details: All Jobs Pass!
    #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  
