name: notify-discord-tests

on:
  pull_request:
    branches:
      - main

jobs:
  notify-broken-test:
    runs-on: ubuntu-latest
    needs: pr-compliance
    steps:
      - name: Interpolate PR Message
        id: pr_message
        run: |
          echo "{pr_message}={[{\"color\":39423,\"title\":\"${{ github.event.pull_request.title }}\",\"url\":\"${{ github.event.pull_request.html_url }}\",\"author\":{\"name\":\"${{ github.event.pull_request.user.login}}\",\"icon_url\":\"${{ github.event.pull_request.user.avatar_url}}\",\"url\":\"${{ github.event.pull_request.user.html_url}}\"},\"description\":\"Branch: ${{ github.event.pull_request.base.ref }}\",\"timestamp\":\"${{ github.event.pull_request.updated_at }}\",\"footer\":{\"text\":\"${{ github.event.repository.full_name }}\",\"icon_url\":\"${{ github.event.repository.owner.avatar_url }}\"}}]} >> $GITHUB_OUTPUT"
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'W3bLocker'
          DISCORD_AVATAR: 'https://i.imgur.com/BPnQGGY.jpeg'
          DISCORD_EMBEDS: ${{ steps.pr_message.outputs.pr_message }}  
         
        uses: Ilshidur/action-discord@master
        with:
          args: ''
