name: Send message to Discord

on:
  pull_request:
    branches:
      - main

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Interpolate PR Message
        id: pr_message
        run: |
          echo "{pr_message}={[{"title": "teste"}]} >> $GITHUB_OUTPUT"
      - name: Send message to Discord
        needs: pr_message
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'W3bLocker'
          DISCORD_AVATAR: 'https://i.imgur.com/BPnQGGY.jpeg'
          DISCORD_EMBEDS: '[{"title": "teste"}]'
