name: Send message to Discord

on:
  pull_request:
    branches:
      - main

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_MESSAGE: A new pull request has been created in the main branch!
        with:
          entryPoint: sendMessage.sh
          args: ${{ env.DISCORD_WEBHOOK_URL }} ${{ env.DISCORD_MESSAGE }}