name: Send message to Discord

on:
  pull_request:
    branches:
      - main

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Interpolate PR Message
        id: pr_message
        run: |
          echo "{pr_message}={[{\"title\": \"teste\"}]} >> $GITHUB_OUTPUT"

      - name: Send message to Discord

        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'W3bLocker'
          DISCORD_AVATAR: 'https://i.imgur.com/BPnQGGY.jpeg'
          DISCORD_EMBEDS: '[{"title": "teste", "author": {"name": "${{ github.event.pull_request.user.login}}", "icon_url": "${{ github.event.pull_request.user.avatar_url }}", "url": "${{ github.event.pull_request.user.html_url}}"}}]'
        uses: Ilshidur/action-discord@master
        with:
          args: ''
