name: PR Compliance

on:
  pull_request_target:
    types: [opened, edited, reopened, ready_for_review]

# Action should have write permission to make updates to PR
permissions:
  pull-requests: write

# jobs:
#   pr-compliance:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: mtfoley/pr-compliance-action@main
#         with:
#           title-check-enable: false
#           body-auto-close: false
#           body-comment: false
#           protected-branch-auto-close: false
#           # all inputs are optional
#           watch-files: |
#             package.json
#             # .env.example
#             # Dockerfile
#             .nvmrc
#             tsconfig.json
  notify:
    runs-on: ubuntu-latest
    # needs: pr-compliance
    steps:
      - name: Interpolate PR Message
        id: pr_message
        run: |
          echo "{pr_message}={[{"title": "teste"}]} >> $GITHUB_OUTPUT"
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 'W3bLocker'
          DISCORD_AVATAR: 'https://i.imgur.com/BPnQGGY.jpeg'
          DISCORD_EMBEDS: ${{ steps.pr_message.outputs.pr_message }}  
         
        uses: Ilshidur/action-discord@master
        with:
          args: ''
